/*
MIT License
Copyright (c) 2024 light config https://gitee.com/lsw-elecm/light_config

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/* This file is automatically generated by the light config tool, do not modify this file */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define LC_TOPDIR   F:/light_config/test
#define dehfh
#define TDWUEFYUEWYF   wggww
#define GDJHECJ   7878.787878
#define SOURCE   CSRC/ZZ/YYwggww
#define dhwejkc   0
#define OS_TOPDIR   .
#define CXXSRC   ./dhwehe.c
#define XX   n74827384732
#define CFG   yutieurtieur
#define BAUD   9600
#define IO   -$(dwefj)A
#define GDJHECJ   0x800
#define MY_PATH   subdir
#define yudywud
#define CFG_UART_INT   "r387r8347t"
#define CFG_UART_INT   'r78374t8347t'
#define CFG_UART_INT   672684738
#define CFG_UART_INT   dwklwekclewn72384723952
#define SUYUFEU   242%26743680350yiwi/stm32f103.c
#define YDYRYE   F:/light_config/test/DLWLEW
#define SUBDIR   F:/light_config/test/subdir
#define HJHFJHDJ   F:/light_config/test/DLWLEW/74932859
#define TYTYTY   HEFHKEJF:/light_config/test/DLWLEWKWJEKJC dwklwekclewn72384723952 wegweg"jdoejf"
#define fehfherjhj   djwjkwejcwkelc kjck ej "dkjwekf"
#define uudiweuci   "hde""wjk  "hcicijwijviwejivjew
#define dhwejkc
#define uudiweuci   "hde""wjk  "hcicijwijviwejivjew
#define hwfwkejfk   jk

#endif /* __CONFIG_H__*/
