# MIT License
# Copyright (c) 2024 light config  https://gitee.com/lsw-elecm/light_config
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This file is automatically generated by the light config tool, do not modify this file


LC_TOPDIR = F:/light_config/test
dehfh = y
ZZ ?= fwefefwe
UU := wgwg
afasgasg = n
dhwjhjweh += y
BAUD ?= 9600
CSRC = n
TDWUEFYUEWYF = wggww
GDJHECJ = n
SOURCE = CSRC/ZZ/YYwggww
gwgewhwh = n
dhwejkc = 0
dwjekwje += flek
OS_TOPDIR = .
CXXSRC = ./dhwehe.c
CXXSRC += ./test.c
CXXSRC += ./dwefewvewve.c
XX = n74827384732
CFG = yutieurtieur
BAUD = 9600
IO = -$(dwefj)A
GDJHECJ = 0x800
MY_PATH = subdir
DUIEUFIE ?= YUWYFIWFI
UART := n72384723952
yudywud = y
CFG_UART_INT = n
CFG_UART_INT = "r387r8347t"
CFG_UART_INT = 'r78374t8347t'
CFG_UART_INT = 672684738
CFG_UART_INT = dwklwekclewn72384723952
SUYUFEU = 242%26743680350yiwi/stm32f103.c
DUIEUI += "7HJDHJHJ"
YDYRYE = F:/light_config/test/DLWLEW
tstrtds = n
SUBDIR = F:/light_config/test/subdir
HJHFJHDJ = F:/light_config/test/DLWLEW/74932859
TYTYTY = HEFHKEJF:/light_config/test/DLWLEWKWJEKJC dwklwekclewn72384723952 wegweg"jdoejf"
fehfherjhj = djwjkwejcwkelc kjck ej "dkjwekf"
uudiweuci = "hde""wjk  "hcicijwijviwejivjew
dhwejkc = y
gwgewhwh = n
uudiweuci = "hde""wjk  "hcicijwijviwejivjew
IO = n
YTRTR = n
hwfwkejfk = jk
